export default {
  EMULATOR_HOST: '192.168.50.189',
  EMULATOR_FUNCTIONS_PORT: 5001,
  EMULATOR_FIRESTORE_PORT: 8080,
  EMULATOR_AUTH_PORT: 9099,
  GOOGLE_API_BASE_URL: 'https://maps.googleapis.com/maps/api',
  GOOGLE_API_KEY: 'AIzaSyDSdcWiZMi8BnJaVUyC-3MaBagmiDFx2rI',
};
